#!/bin/bash

sudo apt-get -y install -f libxss1 libappindicator1 libindicator7 
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome*.deb

rm google-chrome-stable*.deb


