#!/bin/bash

echo "---------------------------------------------------------------"
echo "References:"
echo "    https://media.readthedocs.org/pdf/kivy/latest/kivy.pdf  -- page 15"
echo "    https://kivy.org/docs/installation/installation-rpi.html"
echo "---------------------------------------------------------------"

echo "Install Kivy on Ubuntu 17.04"
echo

echo
echo "------------------------"
echo "Installing Dependandcies"
echo "------------------------"
echo

sudo apt-get update
sudo apt-get install -y python-pip build-essential git python python-dev ffmpeg libsdl2-dev \
	libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev \
	libavformat-dev libavcodec-dev zlib1g-dev

echo
echo "--------------------------------------------------------"
echo "Installing Install gstreamer for audio, video (optional)"
echo "--------------------------------------------------------"
echo

sudo apt-get install -y libgstreamer1.0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good
   
echo
echo "-------------------------"
echo "Installing Cython v0.27.3"
echo "-------------------------"
echo

sudo pip3 install -U Cython==0.27.3


echo
echo "---------------------------"
echo "Installing kivy from github"
echo "---------------------------"
echo

sudo pip3 install git+https://github.com/kivy/kivy.git@master   

echo
echo "-----------------"
echo "Installing KivyMD"
echo "-----------------"
echo

cd /tmp
git clone https://gitlab.com/kivymd/KivyMD.git
cd KivyMD
sudo python3 ./setup.py install

echo "cleaning up..."
cd ..
sudo rm -R KivyMD

